FROM openjdk:8u121-jre-alpine 

ADD maven/vanhack-url-rzr-1.0-SNAPSHOT.jar /opt/spring-cloud/lib/vanhack-url-rzr.jar

ENTRYPOINT ["/usr/bin/java"]

CMD ["-jar", "/opt/spring-cloud/lib/vanhack-url-rzr.jar"]

EXPOSE 8080
